### ISSUE TITLE
Adding username to intervals/annotation/badchannels

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#15]
I see that there's now a username field in the CSV file that's saved, but where would that be specified? Perhaps just a dialog box when asking to save to an external file?

Would it be simple to add a user to the badchannels selection as well?

**Comment by luiztauffer** [comment]
@jrliu95 when you create a new interval type, there is a field for 'user name'. I realize now that there's no such option if the user just goes directly adding the already existing 'invalid' type. There are some ways to do it, let me know which one you prefer:

1- For every interval added, it prompts a dialog to enter user_name. This sounds counter-productive, if you're doing it several times

2- User_name is created when interval type is created, like it is now. This is problematic because it can't be changed later, or we would create an option for 'editing' interval types, which sounds like a lot of branching options for the user and, again, counter-productive

3- We create a **session** option, with `user_name` argument initially, on which every alteration will be associated with. The session name would be displayed in the window title, e.g. "ecogVIS - EC122_B22 - session: Luiz" and there would be a button to change it. Every object added would carry the session info with it.

'Intervals' and 'Annotations' are objects, which makes it intuitive to carry a value such as `user_name`, or `session`, or anything similar. 'bad_channels' is a boolean array corresponding to all the channels in the `electrodes` group, it is an electrode property. This would mean associating an `user_name` to each electrode, which might end up being confusing. What do you think? Is it an important feature for you?

**Comment by jrliu95** [comment]
The 3rd option sounds perfect. This way it's not too much extra work for the user.

Selecting bad channels is more standardized across users (basically channels that are either dead, dead with a bunch of noise, or that are constantly riddled with epileptic/otherwise artifacts), so I'm not concerned with attaching user information to that.

The annotations/intervals are much more user specific so that's why it'd be good to have the user information with those.

**Comment by luiztauffer** [comment]
**session** is now in place, annotations and intervals added are now associated with the current session. Users can change sessions name ate File-> session
