### ISSUE TITLE
ERP plot - selecting channels

### ISSUE THREAD

**Issue by jrliu95** [luiztauffer/ecogVIS#17]
Didn't seem to do anything when I selected a few channels. Can you make it emphasize the selected channels in some way?

**Comment by luiztauffer** [comment]
Yes, it would be great to hear what you guys think of that. How would you like this emphasis to be given?
1- Making the unselected region more transparent, so the selected stand out in the grid
2- redraw the grid with only the selected regions. This has the advantage of putting just a small group of channels in the same visual area (no scrolling needed), but of course you would loose the anatomical-spatial reference

**Comment by luiztauffer** [comment]
Please check the current fix, it's looking much better already!

**Comment by jrliu95** [comment]
Yes, I like this fix with making the unselected channels transparent.  If possible, can you make the unselected channels slightly less transparent? They're just a tad too muted right now

**Comment by luiztauffer** [comment]
done.
Perhaps we could go taking note of features such as this (transparency of unselected channels) and later have a dialog for user control of them. Since it is potentially everything in the software, we should be careful to keep this list of features strict to what would improve the regular user experience and not create unnecessary steps or distractions. Just an idea, let me know what you think!

**Comment by jrliu95** [comment]
That sounds fine to me! Nice to have it be versatile
